services:
  - type: web
    name: tiktok-vidiq
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: TIKTOK_CLIENT_KEY
        sync: false
      - key: TIKTOK_CLIENT_SECRET
        sync: false
      - key: USE_UNOFFICIAL
        value: "false"
